### ISSUE TITLE
FirebaseApp.configure() causes crash but is present

### ISSUE THREAD

**Issue by ksigWyatt** [ThriveCommunityChurch/ThriveChurchOfficialApp#57]
### The default Firebase app has not yet been configured. 

> [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization.

>*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The default FIRApp instance must be configured before the default FIRAuthinstance can be initialized. One way to ensure that is to call `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) in the App Delegate's `application:didFinishLaunchingWithOptions:` (`application(_:didFinishLaunchingWithOptions:)` in Swift).'

**Comment by ksigWyatt** [comment]
Removed `Auth.auth().currentUser` from the top variables. Not sure how that would cause a crash on another page but okay then. We're back in business.

**Comment by ndk1996** [comment]
I have the same bug but I dont have any Auth.auth().currentUser variable on top sir

**Comment by suttonau** [comment]
@ksigWyatt Same for me - Everything was working fine but then I made a global variable ` let currentUserId = Auth.auth().currentUser?.uid` and then the app started crashing. Just moved the variable inside my one of my methods and everything is fine now. Thanks for your help I didn't know what was causing the error for a while. I wonder why it does this?

**Comment by ksigWyatt** [comment]
@suttonau @ndk1996 Thanks for your comments. Interesting that @ndk1996 I didn't see your comment until now. 

So when I think about why this might happen (I'm not 100% sure why either). I think this line 
`let currentUserId = Auth.auth().currentUser?.uid` (still happens with `var` too) is an invalid variable declaration because you cannot retrieve `currentUser?.uid`. This is because if there is no user logged in the uid will be `nil`.  Now that wouldn't necessarily cause a crash, by assigning nil to a variable. It can sometimes if you're using `currentUserId` for something. 

But I think ultimately the reason that this happens is because the global variable created is attempting to make this reference to `currentUser` before the app can use `handle` to check if the user is logged in, using something like:

```
// Check status of user
func handleAuthStateChanged(auth: Auth, user: User?) {
	if Auth.auth().currentUser != nil {
		// User is signed in.
		self.dismiss(animated: true, completion: nil)
		print("User is logged in")
	}
	else {
		// Login OR Register -- only if their email is not on file
		//performSegue(withIdentifier: "login", sender: nil)
		print("Not Logged in")
	}
}
```

Once this runs we have the ability to reference anything under `Auth.Auth().currentUser`. Also, this can happen on another thread so there's no way of knowing exactly when this will run. So what I would recommend is include a check in the `AppDelegate`. Or inside your View Controller that you're using `currentUser?.uid`. Making this a local variable solves this issue for this reason. I'd imagine that perhaps using this (might?) work `filepriveate currentUserId = Auth.auth().currentUser?.uid`. But I doubt it. 

Hopefully that helps you guys a little bit with understanding how this happens. Then again that's just what makes sense to me. I could be wrong.

**Comment by ryanrelf** [comment]
I experienced the same issue with the Auth variable. I wanted to access it globally so I created a global variable for it var user = Auth.auth().currentUser - This caused my app to crash.

**Comment by criskgl** [comment]
Im experiencing the same issue when trying to connect sign in button to tab bar view controller
I fixed it redirecting the segway to another view.

**Comment by nikhilagr** [comment]
Even my app is crashing!! How can I access the Auth variable globally? Any help will be appreciated.

**Comment by ksigWyatt** [comment]
@nikhilagr It seems as though you cannot access this globally. You must assign it to a value whenever you want to use it. 

What I'd recommend is something like this:

1. Declare a global variable outside your `init` / `viewDidLoad` method
2. Assign this variable a default value of nil so something like `var currentUser: FirebaseUser? = nil`
    - I believe the type of currentUser is `FirebaseUser` but I may be wrong. Whatever type that is declare it as that.
3. Within your init / viewDidLoad method, assign the current user to your global variable via something like this `currentUser = Auth.auth().currentUser`.
    - NOTE: Assuming that a user is currently logged in, this value will contain something other than nil. You could put a breakpoint here just to verify yourself that this in fact works as we expect.
4. Anyplace within your view controller you need to use the current user. Simply use `self.currentUser`.
    - Now, there is no guarantee that `self.currentUser` will continue to hold this value. If the user is logged out our `self.currentUser` may return to nil. Depending on if it's a reference or value type; [See more on 'Deep Copy vs Shallow Copy'](https://aruniphoneapplication.blogspot.com/2018/07/deep-copy-and-shallow-copy-swift.html)

So I would expect this to work, where you can access `self.currentUser` within a view controller. You (May?) be able to get away with passing it around to other View Controllers within a `DidSet` block, but again if the user logs out, then this value will have changed.

**Comment by nikhilagr** [comment]
@ksigWyatt Thanks a lot!!
It helped me solve the problem.

**Comment by ksigWyatt** [comment]
@nikhilagr No problem. I'm glad I could help you

**Comment by DimNovo** [comment]
> Removed `Auth.auth().currentUser` from the top variables. Not sure how that would cause a crash on another page but okay then. We're back in business.

 !! Thank you very much dr @ksigWyatt !!
